### ISSUE TITLE
Issue with apply_fixtures

### ISSUE THREAD

**Issue by 17lxve** [ChatFAQ/ChatFAQ#115]
Hello !
Following the installation guide, once i get to:

`docker compose -f docker-compose.yaml -f docker-compose.vars.yaml run back poetry run make apply_fixtures`

i get the following error constantly:

Traceback (most recent call last):
  File "/.venv/lib/python3.10/site-packages/django/db/models/options.py", line 669, in get_field
    return self.fields_map[field_name]
KeyError: 'disabled'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.venv/lib/python3.10/site-packages/django/core/serializers/json.py", line 70, in Deserializer
    yield from PythonDeserializer(objects, **options)
  File "/.venv/lib/python3.10/site-packages/django/core/serializers/python.py", line 130, in Deserializer
    field = Model._meta.get_field(field_name)
  File "/.venv/lib/python3.10/site-packages/django/db/models/options.py", line 671, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: RAGConfig has no field named 'disabled'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "//manage.py", line 21, in <module>
    main()
  File "//manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/.venv/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 102, in handle
    self.loaddata(fixture_labels)
  File "/.venv/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 163, in loaddata
    self.load_label(fixture_label)
  File "/.venv/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 251, in load_label
    for obj in objects:
  File "/.venv/lib/python3.10/site-packages/django/core/serializers/json.py", line 74, in Deserializer
    raise DeserializationError() from exc
django.core.serializers.base.DeserializationError: Problem installing fixture '/back/apps/language_model/fixtures/initial.json':
make: *** [Makefile:30: apply_fixtures] Error 1

Meanwhile, the field very much exists:

`
{
    "model": "language_model.ragconfig",
    "pk": 1,
    "fields": {
      "created_date": "2024-04-19T13:21:54.275",
      "updated_date": "2024-04-19T13:21:54.275",
      "name": "default",
      "knowledge_base": 1,
      "llm_config": 1,
      "prompt_config": 1,
      "generation_config": 1,
      "retriever_config": 1,
      "disabled": false,
      "s3_index_path": null,
      "index_status": "no_index"
    }
  }
`

I am confused and ask for help.

**Comment by Hectruendo** [comment]
Hi @17lxve,

We recently updated the RAGConfig model and forgot to update the corresponding fixture. The field _disabled_ was renamed to _enabled_. To fix the issue, simply replace `"disabled": false` with `"enabled": true` in the fixture.

We will be making a significant update to the master branch soon, which will include this fix along with other architectural improvements.

**Comment by Hectruendo** [comment]
Hello again @17lxve,

I wanted to inform you that we've recently pushed significant updates to the master branch, which include the fix for the issue you encountered as well as several architectural improvements. Additionally, we have updated the official documentation to reflect these changes.

We recommend pulling the latest changes from the master branch and following the updated installation guide in the documentation to set up ChatFAQ. You can find the updated guide here: [ChatFAQ Installation Guide](https://chatfaq.readthedocs.io/en/latest/introduction.html).

**Comment by 17lxve** [comment]
Sorry for the late reply, i couldn't access my VPS for a moment and wanted to try before replying

I still get this error:
Traceback (most recent call last):
  File "/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "auth_group" does not exist
LINE 1: UPDATE "auth_group" SET "name" = 'RPC' WHERE "auth_group"."i...
               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "//manage.py", line 21, in <module>
    main()
  File "//manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/.venv/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 102, in handle
    self.loaddata(fixture_labels)
  File "/.venv/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 163, in loaddata
    self.load_label(fixture_label)
  File "/.venv/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 253, in load_label
    if self.save_obj(obj):
  File "/.venv/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 209, in save_obj
    obj.save(using=self.using)
  File "/.venv/lib/python3.10/site-packages/django/core/serializers/base.py", line 288, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 976, in _save_table
    updated = self._do_update(
  File "/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 1040, in _do_update
    return filtered._update(values) > 0
  File "/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1216, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/.venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: Problem installing fixture '/back/apps/people/fixtures/initial.json': Could not load auth.Group(pk=1): relation "auth_group" does not exist
LINE 1: UPDATE "auth_group" SET "name" = 'RPC' WHERE "auth_group"."i...

Meanwhile:

                                List of relations
 Schema |                         Name                         |   Type   |  Owner
--------+------------------------------------------------------+----------+---------
 public | auth_group                                           | table    | chatfaq
 public | auth_group_id_seq                                    | sequence | chatfaq


I am still trying, and will notify you if i find a solution

**Comment by Hectruendo** [comment]
Hi @17lxve,

Thanks for reaching out!

Have you followed the [database setup steps](https://chatfaq.readthedocs.io/en/latest/installation.html#configuration-instructions) as outlined in our documentation?

From the details you've provided, it appears that the Django server is unable to find the tables in the database, despite them existing according to your list of relations.

One possible issue might be that Django is **connecting to a different PostgreSQL instance** than expected. This could occur if you have multiple PostgreSQL instances running, either outside the Docker container or within another Docker context.

I encountered a similar issue before, and it was related to the exact scenario I mentioned.

Please keep me posted with any further progress, and I'll be happy to assist!

**Comment by 17lxve** [comment]
Alright, i will try and restart on a clean VM, and update you by tomorrow.
Thank you very much !
